### PR TITLE
Individual changes from junit 4.12

### PR DESCRIPTION
**Pull request by josephw**
Bring the changes from JUnit's r4.12 tag across to use hamcrest-junit's package names.

This includes a couple of bug fixes (including #5) and behavioural changes as well as a consistent reformatting.

This PR intentionally targets the `1.x.x.x` branch, but these changes also merge cleanly forward to `master`.

### CODE REVIEW

**Comment by marcphilipp** [comment]
@josephw Thanks, LGTM!

**Comment by marcphilipp** [comment]
@npryce @sf105 Can you please take a look?

**Comment by marcphilipp** [comment]
@npryce @sf105 Do you have time to take a look and possible merge this pull request?

**Comment by npryce** [comment]
Merged onto 1.x.x.x. Will merge and push to master shortly.  Sorry about the delay.

**Pull request merged**
