### PR TITLE
Update classes from JUnit

### PR DESCRIPTION
**Pull request by josephw**
A couple of the adopted classes taken from JUnit 4.11 have seen changes or fixes in JUnit 4.12. This PR brings in those changes.

The most notable change is in `ExpectedException`'s handling of `AssertionError` (junit-team/junit#687); being consistent with 4.12 will be helpful for projects moving across to use `hamcrest-junit`.

A test of `MultipleFailureException` is also deleted, as that class is not part of this project.

### CODE REVIEW

**Comment by npryce** [comment]
It's hard to judge these changes.  A lot of them seem to be refactoring (renames etc.) and I'm not sure why you are merging code from 4.10, 4.11 and 4.12.  Could you submit a PR for the ExpectedException changes (https://github.com/junit-team/junit/issues/687) on their own, without the refactoring?  And submit refactoring(s) as separate pull request(s)?

**Comment by josephw** [comment]
You're right, there's a lot in here. This is essentially a merge of `git diff r4.11 r4.12`, leaving JUnit as the record of individual changes.

The field renaming is from [this commit](https://github.com/junit-team/junit/commit/df00d5eced3a7737b88de0f6f9e3673f0cf88f88); there are also some cumulative Javadoc improvements.

The intention is to take the upstream changes as-is, to stay in sync with JUnit, rather than cherry-picking individual changes. Breaking it down into individual changes would essentially be rebuilding two years of JUnit's development history.

There's no code in here from 4.10; those 'Hamcrest-related files from JUnit 4.xx' commits are to allow diffing 4.11 and 4.12 classes and merge only the changes (and, in the future, doing the same with 4.13).

**Comment by npryce** [comment]
We took code from sometime between JUnit 4.11 and JUnit 4.12.  The intent is not to track every commit to JUnit (because JUnit contains things we do *not* want in hamcrest-junit). But we're happy to track behavioural changes until JUnit removes its dependency on hamcrest.  However, if JUnit is not going to do remove its dependency on hamcrest, then there's no point in hamcrest-junit and we'll just delete it.

**Comment by josephw** [comment]
> However, if JUnit is not going to do remove its dependency on hamcrest, then there's no point in hamcrest-junit and we'll just delete it.

To be clear: I'd really like to see that dependency removed, and look forward to a PR being opened against the JUnit 5 branch. This PR is prompted by an attempt to get another project (Mockito) onto `java-hamcrest` and `hamcrest-junit`.

> The intent is not to track every commit to JUnit (because JUnit contains things we do not want in hamcrest-junit).

Totally agreed; and that's not the aim here. I'm simply proposing, until those classes are removed from JUnit, that the principle of least surprise is for those specific classes to be identical here, so that it's a swap-in replacement for 4.12.

**Comment by npryce** [comment]
It'd be easier for me if this PR was much smaller.  The list of commits is very confusing.  I'd rather have just the test for the behaviour you want and the smallest diff to the implementation that makes the test class.  If you want to refactor the implementation (rename fields, etc.), then please do that as a separate commit.

**Comment by josephw** [comment]
> It'd be easier for me if this PR was much smaller.

Sure -- fewer commits, or a smaller diff? The former's an option, even if it's something as blunt as a squashing rebase.

>  The list of commits is very confusing.

Okay; I isolated the upstream changes in a branch, to make it easier to track future releases: `gitk` may provide a clearer view here. As I said:

> Breaking it down into individual changes would essentially be rebuilding two years of JUnit's development history.

So before I spend time on that, would you be okay with two separate PRs for the style guide changes from upstream and the change to the `@Rule`?

**Comment by npryce** [comment]
Merged PR#8, which has same changes as a smaller, more easily understood sequence of commits.

**Pull request closed without merging**
